# Generated by Django 4.1.7 on 2023-04-19 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pro_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=1000, null=True)),
                ('category_id', models.CharField(max_length=1000, null=True)),
                ('project_name', models.CharField(max_length=100, null=True)),
                ('project_description', models.TextField(null=True)),
                ('project_code', models.CharField(max_length=1000, null=True)),
                ('project_status', models.CharField(choices=[('NW', 'New'), ('IP', 'In planned'), ('CMP', 'Complated')], default='NW', max_length=100)),
                ('user', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=1000, null=True)),
                ('task_file', models.CharField(max_length=100, null=True)),
                ('task_startdate', models.DateField(null=True)),
                ('task_enddate', models.DateField(null=True)),
                ('task_status', models.CharField(choices=[('NW', 'New'), ('IP', 'In planned'), ('CMP', 'Complated')], default='NW', max_length=100)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
