# Generated by Django 4.1.7 on 2023-03-28 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(max_length=1000, null=True)),
                ('category_id', models.IntegerField(max_length=1000, null=True)),
                ('project_name', models.CharField(max_length=100, null=True)),
                ('project_description', models.CharField(max_length=1000, null=True)),
                ('project_code', models.CharField(max_length=100, null=True)),
                ('project_startdate', models.DateField(auto_now_add=True)),
                ('project_enddate', models.DateField()),
                ('project_status', models.CharField(choices=[('NW', 'New'), ('IP', 'In planned'), ('CMP', 'Complated')], default='NW', max_length=100)),
                ('user', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
