# Generated by Django 4.1.7 on 2023-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
