# Generated by Django 4.1.7 on 2023-04-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('week_number', models.CharField(max_length=2, null=True)),
                ('finish_date', models.DateField()),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.task')),
            ],
        ),
    ]
