# Generated by Django 4.1.7 on 2023-03-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_category_id_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_startdate',
            field=models.DateField(),
        ),
    ]
