# Generated by Django 4.1.7 on 2023-03-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_project_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_startdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
