# Generated by Django 4.1.7 on 2023-03-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_project_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_enddate',
        ),
    ]
