# Generated by Django 4.1.7 on 2023-04-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Book',
        ),
    ]
