# Generated by Django 4.1.7 on 2023-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_task_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
