# Generated by Django 4.1.7 on 2023-04-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_project_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_enddate',
            field=models.DateField(null=True),
        ),
    ]
