# Generated by Django 4.1.7 on 2023-04-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_project_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_startdate',
            field=models.DateField(null=True),
        ),
    ]
