# Generated by Django 4.1.7 on 2023-04-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, null=True)),
                ('task_file', models.CharField(max_length=100, null=True)),
                ('task_startdate', models.DateField(null=True)),
                ('task_enddate', models.DateField(null=True)),
                ('task_status', models.CharField(choices=[('NW', 'New'), ('IP', 'In planned'), ('CMP', 'Complated')], default='NW', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_enddate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_startdate',
        ),
    ]
